---
abstract: 'Base class for pod_example script.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  IO::CaptureOutput: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 1.02
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pod-Example
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.03
  English: 0
  Error::Pure: 0.15
  File::Temp: 0
  IO::Barf: 0.04
  Pod::Example: 0.03
  Readonly: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-Pod-Example
  homepage: https://github.com/tupinek/App-Pod-Example
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: git://github.com/tupinek/App-Pod-Example
version: 0.12
